webex/sdk-component-adapter

rollup.config.js
runtimeHelpers were added to the base babel config in order to get the tests working with observables. 
Also added react rollup configs due to base adapters being part of the components repo.
=> fix(rollup): add babel and react configs

rollup.config.js
```js
Object.defineProperty(exports, 'deconstructHydraId', {
enumerable: true,
get: function get() {
return _uuidUtils.deconstructHydraId;
}
});
```
will force us to use `custom exports` for the methods to be appropriately exported. 
Also, I turned on the `Prod` env to build.
=> @webex/common custom export - rollup

package-lock.json, package.json, rollup.config.js
Moving RxJS as a peer dependency instead of bundling it with the adapter code.
An issue of incompatible RxJS libraries was found when trying to use the SDK adapter with `create-react-app` + RxJS.
=> RxJS as peer dependency

src/PeopleSDKAdapter.js, src/PeopleSDKAdapter.test.js
Whenever a user did not have presence enabled, the observables returned from `getMe()` and `getPerson()` would error out.
This PR handles users with a disabled presence (status in Teams).
In practice, this makes the observable error out in the components and also complete the observables when they were expected to be kept alive.
=> getMe() and getPerson() handle users with no presence

src/MeetingsSDKAdapter.js
The JS SDK's `addMedia` function requires the media settings to have the key `mediaSettings`.
=> fix(share): use correct key value for media settings

src/MeetingsSDKAdapter.js
Fixes an issue where user can not mute or unmute if they join a meeting when the set their audio to be muted before joining meeting
when joining a meeting localAudio can't be set to null until tracks have been added to the local stream for audio
Fixes #SPARK-[148175](https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-148174)
=> Fix Audio and Video Mute at Join

rollup.config.js
This PR is to fix [SPARK-106451](https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-106451) where we do not include @webex/common as an external dependency as the current workaround.  The common JS plugin for rollup needs to have namedExports in order to find the code properly please see here
https://rollupjs.org/guide/en/#error-name-is-not-exported-by-module
=> fix(rollup): remove webex/common from external add as named export

package-lock.json, package.json
Also adds a babel config to fix test running.
Further reading: https://stackoverflow.com/questions/51860043/javascript-es6-typeerror-class-constructor-client-cannot-be-invoked-without-ne
=> Update component adapter interfaces to v1.11.0

src/MeetingsSDKAdapter.js
It will fix error get due to localAudio and local Video null. 
**Description**
I got this error when testing calling locally in Cantina. It doesn't occur usually I guess. I was using Desktop with having no input connected and no camera device connected. It might be occur due to other reason also. As  I seen there was Cors policy error above it.
=> fix(meetingsSDKAdapter):  check media stream exists before getting tracks when joining

package.json, scripts/index.html, scripts/puppeteer.server.js
This adds features to the `npm run serve` functionality that allows the user to input an access token instead of pulling from the .env file (thus making it more useful for automation tests in the future). Also adds membership support but is blocked by #77. 
The browserslist addition to `package.json` is required to be able to run `npm run serve` with the latest `webex` package. I've run a `npm run build` and `npm link` for the package to verify the browserslist addition didn't break anything and it works as expected when used in the widget repo.
=> Server improvements

src/MembershipsSDKAdapter.js, src/MembershipsSDKAdapter.test.js
getmembersFromDestination should return an observable that emits member lists (instead of membership objects).
Contains changes from PR https://github.com/webex/sdk-component-adapter/pull/91, which should be merged first.
=> refactor(MembershipsSdkAdapter): emit member lists from getMembersFromDestination

src/MembershipsSDKAdapter.js, src/MembershipsSDKAdapter.test.js, src/mockSdk.js
https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-220419
I changed mockSdk to match with real data from webex.
The real data:
The previous mock data
=> feat(MembershipsSdkAdapter): add orgID field to meeting members

src/MembershipsSDKAdapter.js, src/MembershipsSDKAdapter.test.js
Update the MembershipsSDKAdapter to use "ID" for member id. 
The Sdk adapter implementation should be aligned with the interface definition.
https://github.com/webex/component-adapter-interfaces/blob/master/src/MembershipsAdapter.js#L9
Link Jira sub-task: https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-222995
=> refactor(MembershipsSdkAdapter): rename member id field from "id" to "ID"

src/MeetingsSDKAdapter.js, src/MeetingsSDKAdapter.test.js
Update the MeetingsSdkAdapter to use the correct sharing icon. (share-screen-presence-stroke)
Link bug in Jira: https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-223771
subtask for this repo: https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-224249
=> fix(MeetingsSdkAdapter): update screen sharing icon

src/MeetingsSDKAdapter.js, src/MeetingsSDKAdapter.test.js
Update the MeetingsSdkAdapter to set size on each control icon. 
(cancel_28,microphone-muted_28,camera-muted_28,share-screen-presence-stroke_26,participant-list_28)
Link bug in Jira: https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-223771
subtask for this repo: https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-224821
=> fix(MeetingsSdkAdapter): set size on each control icon

src/MeetingsSDKAdapter.js, src/index.js, src/polyfills.js
When a user disables camera or denies access to it, a javascript error is displayed in the console and the meeting does not start. This PR solves this bug.
https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-229325
=> fix(MeetingsSdkAdapter): prevent JavaScript errors when access to camera/microphone is denied

src/MeetingsSDKAdapter.js, src/MeetingsSDKAdapter.test.js, src/mockSdk.js
Fix the local share property to be updated  depending on the sdk event when the local share is stopped.
https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-233449
=> fix(MeetingSdkAdapter): share button doesn't update the display

src/MeetingsSDKAdapter.js
Update the SDK meeting by calling the .updateVideo method for a live-switching camera effect.
https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-247118
=> feat(MeetingsSdkAdapter): allow switching camera after joining the meeting

src/MeetingsSDKAdapter.js
Update the SDK meeting by calling the .updateAudio method for a live-switching microphone effect.
https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-247114
=> feat(MeetingsSdkAdapter): allow switching microphone after joining the meeting

jest.setup.js, package.json, src/MeetingsSDKAdapter.test.js, src/mockSdk.js
https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-249002
=> fix(MeetingSdkAdapter): modify meeting tests to use MediaStream-like objects

src/MeetingsSDKAdapter.js, src/MeetingsSDKAdapter.test.js
This Pr is for using the getMeeting adapter function for the audio and video controls
https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-250022
=> fix(MeetingsSdkAdapter): use getMeeting for audio and video controls

src/MeetingsSDKAdapter.js
Remove emitting of stop media events from leaveMeeting and call the removeMedia method from inside it. 
https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-250320
=> feat(MeetingSdkAdapter): remove media before leave meeting

src/MeetingsSDKAdapter.js, src/MeetingsSDKAdapter.test.js, src/MeetingsSDKAdapter/controls/MeetingControl.js, src/MeetingsSDKAdapter/controls/RosterControl.js, src/MeetingsSDKAdapter/controls/RosterControl.test.js, src/MeetingsSDKAdapter/controls/index.js
For better encapsulation and code that is easier to maintain, the roster control functions (display & action) have been moved from the main meetings adapter file to individual files that are easier to read and maintain (eg. src/MeetingsSDKAdapter/controls/RosterControl.js). A test file for this functions has also been created.
https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-242543
=> feat(MeetingSdkAdapter): implement roster control in its own file and create the tests accordingly

src/MeetingsSDKAdapter.js, src/MeetingsSDKAdapter.test.js, src/MeetingsSDKAdapter/controls/SettingsControl.js, src/MeetingsSDKAdapter/controls/SettingsControl.test.js, src/MeetingsSDKAdapter/controls/index.js
For better encapsulation and code that is easier to maintain, the settings control functions (display & action) have been moved from the main meetings adapter file to individual files that are easier to read and maintain (eg. src/MeetingsSDKAdapter/controls/SettingsControl.js). A test file for this functions has also been created.
https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-251784
=> feat(MeetingSdkAdapter): implement settings control in its own file and create the tests accordingly

src/MeetingsSDKAdapter.js
This fix was needed because the case when the user closes the screen sharing by clicking the default browser button was not covered by the current implementation.
https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-252776
=> fix(MeetingsSdkAdapter): stop local share stream when EVENT_LOCAL_SHARE_STOP is received from the SDK

jest.setup.js, package.json, src/MeetingsSDKAdapter.test.js, src/mockSdk.js
https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-251321
=> fix(MeetingsSdkAdapter): refactor tests to use global MediaStream mock object

src/MeetingsSDKAdapter.js, src/MeetingsSDKAdapter.test.js, src/MeetingsSDKAdapter/controls/JoinControl.js, src/MeetingsSDKAdapter/controls/JoinControl.test.js, src/MeetingsSDKAdapter/controls/index.js, src/mockSdk.js
For better encapsulation and code that is easier to maintain, the join control functions (display & action) have been moved from the main meetings adapter file to individual files that are easier to read and maintain (eg. src/MeetingsSDKAdapter/controls/JoinControl.js). A test file for this functions has also been created.
=> feat(MeetingSdkAdapter): implement join control in its own file and create the tests accordingly

jest.setup.js, src/MeetingsSDKAdapter.js, src/MeetingsSDKAdapter.test.js, src/MeetingsSDKAdapter/controls/AudioControl.js, src/MeetingsSDKAdapter/controls/AudioControl.test.js, src/MeetingsSDKAdapter/controls/index.js, src/utils.js
For better encapsulation and code that is easier to maintain, the audio control functions (display & action) have been moved from the main meetings adapter file to individual files that are easier to read and maintain (eg. src/MeetingsSDKAdapter/controls/AudioControl.js). A test file for this functions has also been created.
https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-252485
=> feat(MeetingsSdkAdapter): move audio control in a separate file

src/MeetingsSDKAdapter.js, src/MeetingsSDKAdapter.test.js, src/MeetingsSDKAdapter/controls/SwitchSpeakerControl.js, src/MeetingsSDKAdapter/controls/SwitchSpeakerControl.test.js, src/MeetingsSDKAdapter/controls/index.js, src/MeetingsSDKAdapter/testHelper.js
For better encapsulation and code that is easier to maintain, the switch speaker control functions (display & action) have been moved from the main meetings adapter file to individual files that are easier to read and maintain (eg. src/MeetingsSDKAdapter/controls/SwitchSpeakerControl.js). A test file for this functions has also been created.
https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-252483
=> feat(MeetingSdkAdapter): implement switch speaker  in its own file and create the tests accordingly

src/MeetingsSDKAdapter.js, src/MeetingsSDKAdapter.test.js, src/MeetingsSDKAdapter/controls/ProceedWithoutMicrophoneControl.js, src/MeetingsSDKAdapter/controls/ProceedWithoutMicrophoneControl.test.js, src/MeetingsSDKAdapter/controls/index.js
For better encapsulation and code that is easier to maintain, the proceed without microphone control functions (display & action) have been moved from the main meetings adapter file to individual files that are easier to read and maintain (eg. src/MeetingsSDKAdapter/controls/ProceedWithoutMicrophoneControl.js). A test file for this functions has also been created.
https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-254407
=> feat(MeetingsSdkAdapter): move proceed without microphone control in its own file and create tests

src/MeetingsSDKAdapter.js
https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-283306
=> fix(MeetingsSdkAdapter): correct the state of video/audio control when permissions are not granted

src/MeetingsSDKAdapter.js
https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-285596
=> fix(MeetingsSdkAdapter): set preview video stream in correct field when switching camera

.eslintrc.json, jest.setup.js, scripts/index.html, scripts/puppeteer.server.js, src/MeetingsSDKAdapter.js, src/MeetingsSDKAdapter.test.js, src/MeetingsSDKAdapter/controls/SwitchCameraControl.js, src/MeetingsSDKAdapter/controls/SwitchCameraControl.test.js, src/MeetingsSDKAdapter/controls/SwitchMicrophoneControl.js, src/MeetingsSDKAdapter/controls/SwitchMicrophoneControl.test.js, src/MeetingsSDKAdapter/controls/SwitchSpeakerControl.js, src/MeetingsSDKAdapter/controls/SwitchSpeakerControl.test.js
Refactored getAvailableDevices to return an observable dependent on the media stream permission status (eg: meeting.localVideo.permission). When the permission changes, a new list of devices is emitted. If the permission is not 'ALLOWED' (user did not allow or device disabled from operating system), an empty device list is emitted to prevent the device dropdowns in Settings to be populated with unusable devices. With zero options, those dropdowns will be disabled.
https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-290120
=> feat(MeetingsSdkAdapter): emit empty list from getAvailableDevices() if media not accessible

jest.setup.js, src/logger.js, src/utils.js
There are some logger-generated errors when logging some memberships objects received from the SDK that I would like to prevent.
=> fix(logger): prevent logger js errors by handling logging objects with circular references

src/RoomsSDKAdapter.js, src/RoomsSDKAdapter.test.js, src/mockActivities.js, src/mockSdk.js
Added unit tests and logic to handle fetching previous activities. 
Example Usage:
```javascript
const webex = new Webex({
credentials: process.env.WEBEX_ACCESS_TOKEN,
});
const webexSDKAdapter = new WebexSDKAdapter(webex);
// Populate the cache for lookup for roomId
await webexSDKAdapter.datasource.internal.conversation.list({isFavorite: true})
// Subscribe to getPreviousActivites - This will be populated when hasMoreActivites runs
webexSDKAdapter.roomsAdapter.getPreviousActivities(roomId, 10)
.subscribe({
next(val) {
console.log('Fetching past activities');
console.table(val);
webexSDKAdapter.roomsAdapter.hasMoreActivities(roomId);
},
complete(val) {
console.log(webexSDKAdapter.roomsAdapter.roomActivities);
process.exit(0);
},
error(val) {
console.error(val);
},
});
```
=> feat(rooms): add getPreviousActivities method

src/RoomsSDKAdapter.js
- Fixed return value of `fetchPastActivities` to return array of `ids`
- `getPastActivities` now returns `ids` in `subscribe` method as stated per docs.
=> fix(RoomsAdapter): fix return value of fetchPastActivities

src/ActivitiesSDKAdapter.js, src/RoomsSDKAdapter.js, src/WebexSDKAdapter.js, src/cache.js, src/cache.test.js
- Added `cache` module to handle caching `activities` and `rooms`
- Purpose of this is to reduce calls to server for `getActivity` method, if `getPastActivities` method caches the returned activities, then when `useActivity` hook is ran cache should lookup and return `activity`.
=> feat(cache): add cache module

src/MeetingsSDKAdapter.js, src/MeetingsSDKAdapter.test.js, src/MeetingsSDKAdapter/testHelper.js, src/mockSdk.js
Storing the response for verifyPassword() and fetch details like invalidPassword, failureReason and requiredCaptcha and update the meeting object with these details.
Updated verifyPassword() function to accept captcha as a parameter.
Added a new function to refresh the captcha when needed
JIRA: https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-521834 
Tests Performed:
1. Entered the wrong password several times. Captcha inbox appeared to enter the captcha.
2. Entered incorrect password with the valid captcha code.
3. Entered the correct password with the wrong captcha code.
4. Entered the correct password with a valid captcha code.
Meeting Widget Testing
https://github.com/webex/sdk-component-adapter/assets/65543166/8b6b8ee4-7676-48b2-a122-32a487a7b1d1
Logs …
=> fix(meeting): fetching captcha details within meeting object

package.json
This PR is to remove the `engines` keyword from the sdk-component-adapter package as it's breaking installs on downstream applications like Instant Connect even though they are not directly dependent on this package.
```
error @webex/sdk-component-adapter@1.112.7: The engine "node" is incompatible with this module. Expected version ">=20.13.1". Got "16.20.2"
error Found incompatible module.
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
```
=> fix(package): remove engine requirement from package as this breaks downstream app upgrades

src/MeetingsSDKAdapter.js, src/MeetingsSDKAdapter.test.js
Issue: Not showing password popup when click join meeting after dismissing initial popup.
Fix: added condition to check passwordRequired and empty options to updateMeeting with passwordRequired true
https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-557507
=> fix(MeetingsSdkAdapter): handle joinMeeting with empty password

src/MeetingsSDKAdapter.js, src/MeetingsSDKAdapter.test.js
Issue: Meeting name not showing in meeting widget instead it shows sip address.
Fix: added update title code in fetchMeetingInfo.topic
https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-566707
ser-attachments/assets/8e1c0bb1-686a-41a0-9bb6-da2a5398a4c7)
=> fix: update meeting name after fetch meetinginfo

package-lock.json, package.json, src/MeetingsSDKAdapter.js
Upgrade webex package version to the latest 2.x as this is causing errors on widgets while resolving webex versions across different packages.
Please do [see this PR](https://github.com/webex/webex-js-sdk/pull/3902#issue-2578353659) for more context that changes made in the file ` MeetingSDKAdapter.js`
- Previously it has been like `name: options:name` , now I am Assigning the `options.name` to the `alias` because the SDK options contain the parameter as the alias, not a name
=> fix(webex): upgrade webex to latest version

src/MeetingsSDKAdapter/controls/AudioControl.js, src/MeetingsSDKAdapter/controls/AudioControl.test.js, src/MeetingsSDKAdapter/controls/ExitControl.js, src/MeetingsSDKAdapter/controls/ExitControl.test.js, src/MeetingsSDKAdapter/controls/JoinControl.js, src/MeetingsSDKAdapter/controls/JoinControl.test.js, src/MeetingsSDKAdapter/controls/RosterControl.js, src/MeetingsSDKAdapter/controls/RosterControl.test.js, src/MeetingsSDKAdapter/controls/SettingsControl.js, src/MeetingsSDKAdapter/controls/SettingsControl.test.js, src/MeetingsSDKAdapter/controls/ShareControl.js, src/MeetingsSDKAdapter/controls/ShareControl.test.js, src/MeetingsSDKAdapter/controls/SwitchCameraControl.js, src/MeetingsSDKAdapter/controls/SwitchCameraControl.test.js, src/MeetingsSDKAdapter/controls/SwitchMicrophoneControl.js, src/MeetingsSDKAdapter/controls/SwitchMicrophoneControl.test.js, src/MeetingsSDKAdapter/controls/SwitchSpeakerControl.js, src/MeetingsSDKAdapter/controls/SwitchSpeakerControl.test.js, src/MeetingsSDKAdapter/controls/VideoControl.js, src/MeetingsSDKAdapter/controls/VideoControl.test.js
Since we've added the password flow into the Webex Meeting Widget, there is an ask for a developer to pass the meeting password as well as participant name programmatically into the Meeting Widget instead of asking users to enter this once the widget loads up. With this PR, developers will now be able to pass participantName and meetingPasswordOrPin props into the WebexMeetingWidget which will allow users to bypass the authentication and directly land into the Interstitial screen where they can set up audio and video.
Post this, they can directly click "Join Meeting" to start the meeting on the widget.
This allows developers to programmatically insert the password and name into the widget and avoid having to pass this information to a user in an out-of-band manner.
Check the comments in …
=> feat(meeting): enable input of password and name while initializing widget
