webex/sdk-component-adapter

.circleci/config.yml, package-lock.json, package.json, src/index.test.js
Ci config needs to be updated. so wait for the CI PR to get merged first.
=> Unit Testing setup

.gitignore, package-lock.json, package.json, src/RoomsSDKAdapter.js, src/RoomsSDKAdapter.test.js, src/WebexSDKAdapter.js, src/WebexSDKAdapter.test.js, src/__mocks__/sdk.js, src/index.test.js
Builds on #8 
https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-98330
=> Rooms adapter

src/RoomsSDKAdapter.js
Instead of an observable per subscription, there will be one multicast observable per room ID.
To see the difference, you may use the following script:
```js
import Webex from 'webex';
import WebexSDKAdapter from './src/WebexSDKAdapter';
const accessToken = 'your access token';
const roomID = 'sample room ID';
const webex = new Webex({
credentials: accessToken,
});
const adapter = new WebexSDKAdapter(webex);
const first = adapter.roomsAdapter.getRoom(roomID).subscribe(
(room) => {
console.log('Subscription 1');
console.log({room});
},
(error) => {
console.error(error);
}
);
const second = adapter.roomsAdapter.getRoom(roomID).subscribe(
(room) => {
console.log('Subscription 2');
console.log({room});
},
(error) => {
console.error(error);
}
);
const third = …
```
=> perf(RoomsSdkAdapter): modify getRoom to return multicast observable

README.md, src/index.js
To trigger the release process.
=> Export Default Webex Adapter

package-lock.json, package.json, scripts/start.js, src/RoomsSDKAdapter.js
ATM, `eslint` does not lint the scripts and I don't mind that. I'm assuming this `start.js` file will never be committed again.
=> Setup Dev Environment

README.md, package-lock.json, package.json, src/PeopleSDKAdapter.js, src/PeopleSDKAdapter.test.js, src/WebexSDKAdapter.js, src/__mocks__/sdk.js
=> feat(PeopleSdkAdapter): implement adapter

package-lock.json, package.json, src/RoomsSDKAdapter.integration.test.js, src/RoomsSDKAdapter.js, src/testHelper.js
Adding integration tests for rooms adapter, utilizing the Webex SDK.
=> Rooms adapter integration tests

src/RoomsSDKAdapter.integration.test.js, src/WebexSDKAdapter.js, src/testHelper.js
Implement `connect/disconnect` inside `webexSDKAdapter` and apply the changes where necessary.
=> SDK Adapter connect/disconnect

src/PeopleSDKAdapter.integration.test.js, src/RoomsSDKAdapter.integration.test.js, src/testHelper.js
=> SDK Adapter - PeopleSDKAdapter test integration

package-lock.json, package.json, src/MeetingsSDKAdapter.js, src/MeetingsSDKAdapter.test.js, src/__mocks__/sdk.js
awaits for https://github.com/webex/sdk-component-adapter/pull/27 to get merged
=> Implement Join Meeting Method

.eslintrc, src/MeetingsSDKAdapter.js, src/MeetingsSDKAdapter.test.js, src/__mocks__/sdk.js
Action Items (commits):
1 - mute functionalities
2 - unmute functionalities --> different PR prolly
3 - displayData functionalities
4 - (bugfix) localAudio and video must be streams not tracks
=> Mute Audio & Video

src/MeetingsSDKAdapter.js, src/MeetingsSDKAdapter.test.js, src/__mocks__/sdk.js
1 - mute/unmute for video/audio
2 - convert `then` to `async/await` 🙄 @lalli-flores 
3 - make control naming conventions more abstract
=> Handle Audio/Video Controls

src/PeopleSDKAdapter.integration.test.js, src/PeopleSDKAdapter.js, src/__mocks__/sdk.js
getMe() should only fetches and emits the data once!
=> Improve getMe()

CONTRIBUTING.md
At the request of @InteractiveTimmy, the grammar structure of number 8 was off.
=> docs(contributing): update sentence structure

scripts/index.html, scripts/puppeteer.server.js, src/MeetingsSDKAdapter.js, src/MeetingsSDKAdapter.test.js, src/__mocks__/sdk.js
To implement the sharing feature, I added ```handleLocalShare``` and ```shareControl``` to connect to webex-js-sdk to start/stop sharing, and emit sharing status to upper UI level.
=> Add Screen Sharing Meeting Control

src/MembershipsSDKAdapter.js, src/MembershipsSDKAdapter.test.js, src/WebexSDKAdapter.js, src/__mocks__/sdk.js
https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-174910
=> feat(MembershipsSdkAdapter): add meeting support

src/MeetingsSDKAdapter.js, src/MeetingsSDKAdapter.test.js
https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-175408
Manually tested with the server and it removed/added remote share in the dom as expected!
=> Remote share event support

src/MembershipsSDKAdapter.js, src/__mocks__/sdk.js
Was doing the opposite of getting active members. Tests updated.
=> fix(MembershipsSdkAdapter): get in meeting members

src/MembershipsSDKAdapter.js, src/MembershipsSDKAdapter.test.js, src/mockSdk.js
Fix tests and bugs that were introduced in the master branch in this PR
https://github.com/webex/sdk-component-adapter/pull/90
@lalli-flores
=> fix(MembershipsSdkAdapter): fix test

package.json, src/MembershipsSDKAdapter.js, src/mockSdk.js
- 'member' object changed a property name.
=> fix(memberships): update Webex SDK

src/MembershipsSDKAdapter.js, src/MembershipsSDKAdapter.test.js, src/mockSdk.js
Update SDK Adapter to send a sharing status for a member
=> feat(MembershipsSdkAdapter): return the sharing status of each member

__mocks__/@webex/common.js, src/MembershipsSDKAdapter.js, src/MembershipsSDKAdapter.test.js, src/mockSdk.js
add the ability to return members of a room using `roomID` as an identifier 
https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-154240
=> feat(MembershipsSdkAdapter): return members of a room

package.json, rollup.config.js, src/MembershipsSDKAdapter.js, src/MembershipsSDKAdapter.test.js, src/mockSdk.js
Fix tests and bugs that were introduced in the master branch in this PR https://github.com/webex/sdk-component-adapter/pull/93
https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-223388
=> fix(MembershipsSdkAdapter): add unresolvable named export SDK_EVENT

scripts/index.html, scripts/puppeteer.server.js, src/MeetingsSDKAdapter.js, src/MeetingsSDKAdapter.test.js
Add member roster control to give the possibility to show/hide roster of a given meeting id
https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-220024
=> feat(MeetingSdkAdapter): add member-roster control

src/MembershipsSDKAdapter.js, src/MembershipsSDKAdapter.test.js, src/mockSdk.js
Add host field for membership members
Link Jira :  https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-222975
=> feat(MembershipsSdkAdapter): add boolean host field to emitted membership members

package-lock.json, package.json, src/OrganizationsSDKAdapter.js, src/OrganizationsSDKAdapter.test.js, src/WebexSDKAdapter.js, src/mockSdk.js
Implement organizations adapter
https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-220451
=> feat(OrganizationsSdkAdaper): add organizations adapter

src/MembershipsSDKAdapter.js, src/MembershipsSDKAdapter.test.js, src/mockSdk.js
Add guest field for membership members 
https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-222986
=> feat(MembershipsSdkAdapter): add boolean guest field to emitted membership members

src/MembershipsSDKAdapter.js, src/MembershipsSDKAdapter.test.js, src/mockSdk.js
https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-223552
=> refactor(MembershipsSdkAdapter): sort the members in a meeting

src/MeetingsSDKAdapter.js, src/MeetingsSDKAdapter.test.js
https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-223892
https://user-images.githubusercontent.com/8277264/114510157-ff4bdf80-9c3e-11eb-98ee-192bcccb5611.mov
=> feat(MeetingSdkAdapter): add state for meeting

__mocks__/@webex/common.js, src/MembershipsSDKAdapter.js, src/MembershipsSDKAdapter.test.js, src/PeopleSDKAdapter.test.js, src/mockSdk.js
https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-223396
=> refactor(MembershipsSdkAdapter): sort the members in a room

src/WebexSDKAdapter.js
refactor(WebexSdkAdapter): extend all JSON adapter classes from interfaces
https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-232567
=> refactor(WebexSdkAdapter): extend all json adapter classes from interfaces

.github/workflows/update-dependencies.yml
Auto update interfaces dependency on a version change event.
Addresses [SPARK-227494](https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-227494)
=> build(workflow): update dependency on event

__mocks__/@webex/common.js, rollup.config.js, src/MembershipsSDKAdapter.js, src/mockSdk.js
Update member id from member object to retrieve the id from participant person id
=> fix(MembershipSdkAdapter): change member id to take the value from participant

package-lock.json, package.json
This PR is about updating the component-adapter-interfaces version
=> fix(package): update component adapter interfaces to v1.17.0

scripts/index.html, scripts/puppeteer.server.js, src/MeetingsSDKAdapter.js
https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-235291
=> feat(MeetingSdkAdapter): add settings control

package-lock.json, package.json
- add browser list config
- update the package-lock file with latest browser list version
https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-195670
=> build(package.json): add browser list config

scripts/puppeteer.server.js, src/MeetingsSDKAdapter.js, src/MeetingsSDKAdapter.test.js
Disable audio mute and video mute controls if there are no media devices available or allowed.
https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-227511
=> feat(MeetingSdkAdapter): disable audio/video controls when no media

scripts/index.html, scripts/puppeteer.server.js, src/MeetingsSDKAdapter.js, src/MeetingsSDKAdapter.test.js
Create camera control for the cases when the users have more then one camera.
https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-238419
=> feat(MeetingsSdkAdapter): add camera selection control

src/MeetingsSDKAdapter.js, src/MeetingsSDKAdapter.test.js, src/retro 2021-05-19.txt
Set audio/video permission before and after user input
=> feat(MeetingsSdkAdapter): set audio/video permissions before and after asking the user for access to local media

scripts/index.html, scripts/puppeteer.server.js, src/MeetingsSDKAdapter.js, src/MeetingsSDKAdapter.test.js
Add microphone selection control
https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-240658
=> feat(MeetingsSdkAdapter): add microphone selection control

scripts/index.html, scripts/puppeteer.server.js, src/MeetingsSDKAdapter.js, src/MeetingsSDKAdapter.test.js
Add speaker selection control 
https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-243984
=> feat(MeetingsSdkAdapter): add speaker selection control

src/MeetingsSDKAdapter.js
https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-249004
=> fix(MeetingsSdkAdapter): keep only audio (video) tracks in audio (video) streams

scripts/puppeteer.server.js, src/MeetingsSDKAdapter.js, src/MeetingsSDKAdapter.test.js
Transform localAudio and localVideo properties into objects containing "stream" and "permission" properties. 
https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-247395
=> feat(MeetingSdkAdapter): transform localAudio and localVideo into objects

src/MeetingsSDKAdapter.js
This PR is about stopping local share stream immediately after clicking the stop share button in order to circumvent the sdk limitation of taking a long time to do this action.
https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-248592
=> fix(MeetingSdkAdapter): stop local sharing stream immediately after clicking the stop share button

src/MeetingsSDKAdapter.js
In Webex Widgets, inside the Modal Settings, it seems the selected options are not preserved after their selection.
=> fix(dropdown-controls): select initial value

src/MeetingsSDKAdapter.js
https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-251004
=> fix(MeetingsSdkAdapter): make getMeeting observable also emit messages emitted by createMeeting

src/MeetingsSDKAdapter.js
https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-251181
=> fix(MeetingSdkAdapter): access the local share stream correctly in handleLocalShare()

src/MeetingsSDKAdapter.js
Add no-devices control when there are no devices
=> feat(MeetingsSdkAdapter): Add no devices messages to dropdown controls

scripts/index.html, scripts/puppeteer.server.js, src/MeetingsSDKAdapter.js, src/MeetingsSDKAdapter.test.js
Create "proceed without camera" control display and action 
https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-231517
=> feat(MeetingsSdkAdapter): implement proceed without camera control

src/MeetingsSDKAdapter.js, src/utils.js
Task link: https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-252133
=> fix(MeetingsSdkAdapter): chain dependent observables on createMeeting

src/MeetingsSDKAdapter.js, src/MeetingsSDKAdapter.test.js
https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-252151
=> feat(MeetingsSdkAdapter): remove "Personal Room" from meeting title

src/MeetingsSDKAdapter.js
Task link:  https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-252912
=> feat(MeetingsSdkAdapter): avoid emitting 'asking' state on media request when user already allowed or denied access

scripts/index.html, scripts/puppeteer.server.js, src/MeetingsSDKAdapter.js, src/MeetingsSDKAdapter.test.js
Create "proceed without microphone" control display and action. 
Update getLocalMedia method to use chainWith function for chaining observables.
https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-250019
=> feat(MeetingsSdkAdapter): implement proceed without microphone control

src/MeetingsSDKAdapter.test.js, src/MeetingsSDKAdapter/controls/RosterControl.test.js, src/MeetingsSDKAdapter/controls/SettingsControl.test.js, src/MeetingsSDKAdapter/testHelper.js
https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-253306
=> refactor(MeetingsSdkAdapter): put common meetings sdk adapter initialization code in a function for testing

src/MeetingsSDKAdapter.js, src/MeetingsSDKAdapter.test.js, src/MeetingsSDKAdapter/controls/AudioControl.js, src/MeetingsSDKAdapter/controls/AudioControl.test.js, src/MeetingsSDKAdapter/controls/ExitControl.js, src/MeetingsSDKAdapter/controls/ExitControl.test.js, src/MeetingsSDKAdapter/controls/JoinControl.js, src/MeetingsSDKAdapter/controls/JoinControl.test.js, src/MeetingsSDKAdapter/controls/RosterControl.js, src/MeetingsSDKAdapter/controls/RosterControl.test.js, src/MeetingsSDKAdapter/controls/SettingsControl.js, src/MeetingsSDKAdapter/controls/SettingsControl.test.js, src/MeetingsSDKAdapter/controls/SwitchCameraControl.js, src/MeetingsSDKAdapter/controls/SwitchCameraControl.test.js
https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-256236
=> feat(MeetingControls): add types for meeting controls

src/MeetingsSDKAdapter.js
https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-263004
=> feat(MeetingsSdkAdapter): stop disabled stream when leaving the meeting

src/MeetingsSDKAdapter.js, src/MeetingsSDKAdapter.test.js, src/MeetingsSDKAdapter/controls/RosterControl.js, src/MeetingsSDKAdapter/controls/RosterControl.test.js, src/MeetingsSDKAdapter/controls/SettingsControl.js, src/MeetingsSDKAdapter/controls/SettingsControl.test.js
Add missing text on MeetingSdkAdapter.
https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-264005
=> feat(MeetingsSdkAdapter): add missing text on controls

src/MeetingsSDKAdapter.js
https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-264711
=> fix(MeetingsSdkAdapter): stop stream when switching microphones

src/MembershipsSDKAdapter.js
Check if participants have an organization ID.
=> feat(MembershipsSdkAdapter): check if org id exists

package-lock.json, package.json, src/MeetingsSDKAdapter.test.js
Updating semantic-release to latest:
* semantic-release v18
* @semantic-release/git v10
* @semantic-release/changelog v6
=> build(DevDependencies): update semantic-release to v18

src/MeetingsSDKAdapter.js
https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-271862
=> feat(MeetingsSdkAdapter): create 'supportedControls()' method

src/logger.js
https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-279669
=> fix(logger): add the correct type property of media stream tracks

src/MeetingsSDKAdapter/controls/AudioControl.js, src/MeetingsSDKAdapter/controls/AudioControl.test.js, src/MeetingsSDKAdapter/controls/ProceedWithoutCameraControl.test.js, src/MeetingsSDKAdapter/controls/ProceedWithoutMicrophoneControl.test.js, src/MeetingsSDKAdapter/controls/SettingsControl.js, src/MeetingsSDKAdapter/controls/SettingsControl.test.js, src/MeetingsSDKAdapter/controls/VideoControl.js, src/MeetingsSDKAdapter/controls/VideoControl.test.js
Task link: https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-279683
=> feat(MeetingsSdkAdapter): update meeting controls type

src/OrganizationsSDKAdapter.js, src/OrganizationsSDKAdapter.test.js
Task link: https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-253534
=> feat(OrganizationsSdkAdapter): add debug logs

rollup.config.js, src/logger.js
https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-280427
=> fix(Winston): repair winston export for widgets

scripts/index.html, scripts/puppeteer.server.js
https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-280955
=> feat(scripts): add input elements related to pasword, host key and meeting state in sdk demo page

src/MeetingsSDKAdapter.js, src/MeetingsSDKAdapter.test.js
Task link: https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-273320
=> fix(MeetingsSdkAdapter): show default camera and microphone in webex settings

src/MeetingsSDKAdapter.js, src/MeetingsSDKAdapter.test.js
https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-245926
=> feat(src): replace all console.log/warn/error with Winston logger

package-lock.json, package.json
https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-282395
=> fix(package): update component adapter interfaces to v1.22.0

src/MembershipsSDKAdapter.js
https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-253533
=> feat(MembershipsSdkAdapter): add debug logs

src/MeetingsSDKAdapter/controls/AudioControl.js, src/MeetingsSDKAdapter/controls/ExitControl.js, src/MeetingsSDKAdapter/controls/JoinControl.js, src/MeetingsSDKAdapter/controls/RosterControl.js, src/MeetingsSDKAdapter/controls/SettingsControl.js, src/MeetingsSDKAdapter/controls/ShareControl.js, src/MeetingsSDKAdapter/controls/SwitchCameraControl.js, src/MeetingsSDKAdapter/controls/SwitchMicrophoneControl.js, src/MeetingsSDKAdapter/controls/SwitchSpeakerControl.js, src/MeetingsSDKAdapter/controls/VideoControl.js
https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-283785
=> feat(meeting-controls): add debug logs

src/MeetingsSDKAdapter.js
Task link: https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-283779
=> refactor(MeetingsSdkAdapter): improve debug logs

src/MeetingsSDKAdapter.js, src/MeetingsSDKAdapter.test.js, src/MeetingsSDKAdapter/controls/SwitchSpeakerControl.js, src/MeetingsSDKAdapter/controls/SwitchSpeakerControl.test.js
Task link: https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-284116
=> feat(MeetingsSdkAdapter): add browser default speaker to the available speaker list

package-lock.json, package.json
https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-284126
=> fix(package): update js-sdk to 1.149.2

src/MeetingsSDKAdapter.js
Task link: https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-284393
=> fix(MeetingsSdkAdapter): check settings preview streams before updating sdk local streams

src/MeetingsSDKAdapter.js
Task link: https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-285600
=> fix(MeetingsSdkAdapter): password and hostKey validation

src/MembershipsSDKAdapter.js, src/MembershipsSDKAdapter.test.js
https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-273569
=> feat(MembershipsSdkAdapter): return non-user members from getMembers()

src/MeetingsSDKAdapter.js, src/MeetingsSDKAdapter.test.js, src/MeetingsSDKAdapter/controls/AudioControl.js, src/MeetingsSDKAdapter/controls/VideoControl.js
adds intermediary muting/unmuting states for audio and video controls
https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-285608
=> feat(MeetingsSdkAdapter): add muting/unmuting intermediary states

scripts/index.html, scripts/puppeteer.server.js
- store access token and meeting destination in localStorage
- control labels, tooltips and disabled state
- connecting state and errors
=> feat(puppeteer): testing interface improvements:

src/MembershipsSDKAdapter.js, src/mockSdk.js
https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-285588
=> fix(MembershipsSdkAdapter): treat sdk members with isModerator set to true as meeting hosts

src/MeetingsSDKAdapter.js, src/MeetingsSDKAdapter.test.js
https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-289195
=> feat(MeetingsSdkAdapter): set media permissions according to received sdk media error

scripts/index.html, scripts/puppeteer.server.js, src/MeetingsSDKAdapter.js, src/MeetingsSDKAdapter.test.js, src/mockSdk.js
https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-289107
=>  feat(MeetingsSdkAdapter): add changeLayout function

src/MeetingsSDKAdapter.js, src/MeetingsSDKAdapter.test.js
https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-290113
=> feat(MeetingsSdkAdapter): mapping layout types

src/MeetingsSDKAdapter.js
https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-290480
=> fix(MeetingsSdkAdapter): obtain remote sharing stream for a user who joins after sharing is started

src/ActivitiesSDKAdapter.js, src/WebexSDKAdapter.js
Task link: https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-293304
=> feat(ActivitiesSdkAdapter): implement empty ActivitiesSDKAdapter

src/ActivitiesSDKAdapter.js, src/ActivitiesSDKAdapter.test.js, src/mockSdk.js
https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-293308
=> feat(ActivitiesSdkAdapter): create a method to fetch an activity by id

src/ActivitiesSDKAdapter.js, src/ActivitiesSDKAdapter.test.js, src/mockSdk.js
https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-293312
=> feat(ActivitiesSdkAdapter): implement a method to post an attachment action

__mocks__/@webex/common.js, src/RoomsSDKAdapter.integration.test.js, src/RoomsSDKAdapter.js, src/RoomsSDKAdapter.test.js, src/mockSdk.js
Implement `getRoomActivities`
[SPARK-98332](https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-98332)
=> getRoomActivites

src/ActivitiesSDKAdapter.js, src/ActivitiesSDKAdapter.test.js, src/mockSdk.js
https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-299934
=> feat(ActivitiesSdkAdapter): implement a method to post an activity

src/ActivitiesSDKAdapter.js, src/ActivitiesSDKAdapter.test.js
https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-304126
=> refactor(ActivitiesSdkAdapter): implement methods for card attachments management

package.json, rollup.config.js, src/logger.js
https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-310006
=> fix(logger): replace winston logger with a custom logger

jest.setup.js, src/MeetingsSDKAdapter.js, src/MeetingsSDKAdapter/controls/VideoControl.js
Task link: https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-309634
=> fix(MeetingsSdkAdapter): prevent camera usage on iOS 15.1 due to iOS bug

src/logger.js, src/logger/consoleTransport.js, src/logger/logger.js
https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-311492
=> feat(logger): split logger implementation into separate files and create console transport

src/ActivitiesSDKAdapter.js, src/ActivitiesSDKAdapter.test.js, src/mockSdk.js
- Updated activities adapter to use `request` to fetch from conversations API.
- Updated response to handle parsing and formatting according to same API.
=> feat(activity): change to use conversations API

src/ActivitiesSDKAdapter.js, src/mockSdk.js
https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-312368
=> fix(ActivitiesSdkAdapter): properly transform an activity card into an activity attachment

package-lock.json, package.json, src/RoomsSDKAdapter.integration.test.js, src/RoomsSDKAdapter.js, src/RoomsSDKAdapter.test.js
Update SDK Adapter names to match RoomsAdapter interface
~~Requires `package-lock.json` to be updated once webex/component-adapter-interfaces#82 is merged~~
[SPARK-302946](https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-302946l)
=> refactor(RoomsAdapter): update rooms adapter method names

src/ActivitiesSDKAdapter.js, src/RoomsSDKAdapter.js, src/RoomsSDKAdapter.test.js
- Fixed the current return value of `getActivitiesInRealTime` to have correct IDs using `constructHydraId`
- Added exported `fromSDKActivity`
=> fix(RoomsAdapter): fix return value of getActivitiesInRealTime

src/ActivitiesSDKAdapter.js
- Fixed issue where personID was not transformed to correct type.
=> fix(ActivitiesAdapter): fix personID from sdk activity

jest.setup.js, src/MeetingsSDKAdapter/controls/ShareControl.js
https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-313319
=> feat(ShareControl): disable share screen on mobile browsers and Internet Explorer browser

src/ActivitiesSDKAdapter.js, src/ActivitiesSDKAdapter.test.js
https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-315951
=> feat(ActivitiesSdkAdapter): add 'cards' property to activity and move card from attachments

jest-puppeteer.config.js, jest.setup.js, package-lock.json, package.json, src/PeopleSDKAdapter.integration.test.js, src/RoomsSDKAdapter.integration.test.js
Get integration tests to work
[SPARK-312424](https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-312424)
=> test(tooling): resusciate integration tests

src/ActivitiesSDKAdapter.js, src/ActivitiesSDKAdapter.test.js, src/mockSdk.js
https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-313443
=> feat(ActivitiesSdkAdapter): encrypt cards before posting an activity

src/MeetingsSDKAdapter.js
Task link: https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-318697
=> fix(MeetingsSdkAdapter): avoid disabling audio control if on iOS 15.1

package-lock.json, package.json, src/MembershipsSDKAdapter.js, src/MembershipsSDKAdapter.test.js, src/mockSdk.js
add addRoomMember method to the membershipSDKAdapter.
=> feat(MembershipsAdapter): add addRoomMember method

.circleci/config.yml, src/MeetingsSDKAdapter.js
Fixes the intermittent issue of member being made to leave the meeting (instant) before joining.
JIRA - [SPARK-379330](https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-379330)
=> fix(meeting): fix intermittently leaving meeting before even joining

src/MeetingsSDKAdapter.js
This PR is to trigger the release after updating the github and npm token in the pipeline.
=> fix(meeting): release auto leave intermittently fix

src/MeetingsSDKAdapter.js
=> fix(meeting): fix auto leave intermittently - release

package-lock.json, package.json
Upgrade `webex` package version to the latest 2.x as this is causing errors on `widgets` while resolving webex versions across different packages.
=> fix(webex): upgrade webex to the latest 2.x version

package-lock.json, package.json
Upgrade webex package version to the latest 2.x as this is causing errors on widgets while resolving webex versions across different packages.
https://github.com/user-attachments/assets/6e68c7b8-8b12-4654-9eba-0b94f5484f04
=> fix(webex): upgrade webex to latest version 2.x version
